######################## default configuration ####################
baseURL = "https://www.elivirs.com"
languageCode = "en-us"
title = "Elivir's Cebu Lechon Restaurant | Quezon City"
theme = "hargo"
summaryLength = "20"
paginate = 10

canonifyurls = true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  # [[params.plugins.js]]
  # URL = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
    name = "Affordables"
    url = "affordables"
    weight = 20
    pre = "<svg style='height: 20px !important' fill='dodgerblue' viewBox='0 0 496 512'><path d='M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm80 168c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm-160 0c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm80 256c-60.6 0-134.5-38.3-143.8-93.3-2-11.8 9.3-21.6 20.7-17.9C155.1 330.5 200 336 248 336s92.9-5.5 123.1-15.2c11.3-3.7 22.6 6.1 20.7 17.9-9.3 55-83.2 93.3-143.8 93.3z'/></svg>"

  [[menu.footer]]
    name = "Affordables"
    url = "affordables"
    weight = 20
    pre = "<svg style='height: 20px !important' fill='dodgerblue' viewBox='0 0 496 512'><path d='M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm80 168c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm-160 0c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm80 256c-60.6 0-134.5-38.3-143.8-93.3-2-11.8 9.3-21.6 20.7-17.9C155.1 330.5 200 336 248 336s92.9-5.5 123.1-15.2c11.3-3.7 22.6 6.1 20.7 17.9-9.3 55-83.2 93.3-143.8 93.3z'/></svg>"


#################### default parameters ################################
[params]
logo = "/icons/h.png"
logofooter = "/icons/elivirs.png"
home = "Home"
# Meta data
description = "Elivir's Lechon is the home of affordable and delicious Cebu lechon and other Filipino food"
author = "Pantry Peers"


# gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBQRj0aOxRe0Rk54PliNx6TXEW2BJI1Aww&libraries=places"

# mapLatitude = "14.362047718555887"
# mapLongitude = "121.05771924920946"

# elivirs2: lat 14.663898
# long: 121.069699

# 121.067892
# 14.6631391

# mapMarker = "images/marker.png"
googleAnalitycsID = "G-S3C679T7L1"
# Contact Information
mobile = "+63 969 436 0497"
phone = "+63 2 8 376 6419"
email = "hello@elivirs.com"
# email = "elivirslechon@gmail.com"
location = "Upper Ground Floor, Berkeley Square, Commonwealth Avenue (near Tandang Sora), Old Balara, Quezon City"
# copyright
copyright = "| @2022 [Pantry Peers](https://pantrypoints.com/build) |"
# All Rights Reserved
  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  # enable = false
  # websiteID = "444334"
  # publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "<svg width='15' fill='white' viewBox='0 0 448 512'><!-- Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d='M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z'/></svg>"
  link = "https://www.facebook.com/elivirscebulechon"
  # [[params.social]]
  # icon = "ti-twitter-alt"
  # link = "#"
  
  [[params.social]]
  icon = "<svg width='15' fill='white' viewBox='0 0 576 512'><!-- Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d='M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z'/></svg>"
  link = "https://www.youtube.com/@elivirs"
  #  link = "https://www.youtube.com/channel/UC_XmRSEqWZeIozWdZKLzHJA"
  
  # [[params.social]]
  # icon = "ti-instagram"
  # link = "#"
  
  # [[params.social]]
  # icon = "ti-pinterest"
  # link = "#"

  # Contact Form
  [params.contact]
  formAction = "https://formcarry.com/s/nN_oxJ8Ryot"
  # formAction = "https://hub.pantrypoints.com/api/email"
  # formAction = "https://formcarry.com/s/NUHGWnNKMgb"
  # formAction = "https://formcarry.com/s/YtVOXzTso67"
  